<?php
// echo '<pre>'.print_r($settings,1).'</pre>';
$elem_id = '';
if(isset($settings['popup_id']) && !empty($settings['popup_id'])){
    $elem_id = $settings['popup_id'];
}
else{
    $elem_id ='#catdisp-'.$settings['id'];
}
?>
<style type="text/css">
    <?php
    /* Import google fonts */
    if(isset($settings['google_font']) && $settings['google_font']!=''){
        $google_font = explode('##', $settings['google_font']);
        $font_settings = array();
        $font_settings['name'] =  $google_font['0'];
        $font_url_param = urlencode( $google_font['0'] );
        if($google_font['1']=='regular'){ $google_font['1']='400';}
        $font_url_param .=':wght@'.$google_font['1'];
        echo '@import url(http' . ( is_ssl() ? 's' : '' ) . '://fonts.googleapis.com/css2?family=' . $font_url_param . ');';
    }

    /* Overwrite .row and .col-^ if custom gutter is enabled*/
    if( isset($settings['_catdisp-inbox_custom-gutter-width']) && $settings['_catdisp-inbox_custom-gutter-width']=='1' 
     && isset($settings['_catdisp-inbox_gutter-width']) && $settings['_catdisp-inbox_gutter-width'] !=''){
        $gutter_width = preg_split('/(?<=[0-9])(?=[a-z]+)/i', $settings['_catdisp-inbox_gutter-width']);
 
            echo $elem_id.' .row{
                margin-left: -'.($gutter_width['0']/2).$gutter_width['1'].';
                margin-right: -'.($gutter_width['0']/2).$gutter_width['1'].';
            }';
            echo $elem_id.' .col-1, '.$elem_id.' .col-2, '.$elem_id.' .col-3, '.$elem_id.' .col-4, '.$elem_id.' .col-5, '.$elem_id.' .col-6, '.$elem_id.' .col-7, '.$elem_id.' .col-8, '.$elem_id.' .col-9, '.$elem_id.' .col-10, '.$elem_id.' .col-11, '.$elem_id.' .col-12, '.$elem_id.' .col, '.$elem_id.' .col-auto, '.$elem_id.' .col-sm-1, '.$elem_id.' .col-sm-2, '.$elem_id.' .col-sm-3, '.$elem_id.' .col-sm-4, '.$elem_id.' .col-sm-5, '.$elem_id.' .col-sm-6, '.$elem_id.' .col-sm-7, '.$elem_id.' .col-sm-8, '.$elem_id.' .col-sm-9, '.$elem_id.' .col-sm-10, '.$elem_id.' .col-sm-11, '.$elem_id.' .col-sm-12, '.$elem_id.' .col-sm, '.$elem_id.' .col-sm-auto, '.$elem_id.' .col-md-1, '.$elem_id.' .col-md-2, '.$elem_id.' .col-md-3, '.$elem_id.' .col-md-4, '.$elem_id.' .col-md-5, '.$elem_id.' .col-md-6, '.$elem_id.' .col-md-7, '.$elem_id.' .col-md-8, '.$elem_id.' .col-md-9, '.$elem_id.' .col-md-10, '.$elem_id.' .col-md-11, '.$elem_id.' .col-md-12, '.$elem_id.' .col-md, '.$elem_id.' .col-md-auto, '.$elem_id.' .col-lg-1, '.$elem_id.' .col-lg-2, '.$elem_id.' .col-lg-3, '.$elem_id.' .col-lg-4, '.$elem_id.' .col-lg-5, '.$elem_id.' .col-lg-6, '.$elem_id.' .col-lg-7, '.$elem_id.' .col-lg-8, '.$elem_id.' .col-lg-9, '.$elem_id.' .col-lg-10, '.$elem_id.' .col-lg-11, '.$elem_id.' .col-lg-12, '.$elem_id.' .col-lg, '.$elem_id.' .col-lg-auto, '.$elem_id.' .col-xl-1, '.$elem_id.' .col-xl-2, '.$elem_id.' .col-xl-3, '.$elem_id.' .col-xl-4, '.$elem_id.' .col-xl-5, '.$elem_id.' .col-xl-6, '.$elem_id.' .col-xl-7, '.$elem_id.' .col-xl-8, '.$elem_id.' .col-xl-9, '.$elem_id.' .col-xl-10, '.$elem_id.' .col-xl-11, '.$elem_id.' .col-xl-12, '.$elem_id.' .col-xl, '.$elem_id.' .col-xl-auto{
                padding-right: '.($gutter_width['0']/2).$gutter_width['1'].';
                padding-left: '.($gutter_width['0']/2).$gutter_width['1'].';
            }';

       
    }

    /* Style generated by the custom settings */
        foreach($settings['elements'] as $class => $element ){

            if($element['normal']){
                echo "body ".$elem_id." .".$class.'{';
                foreach($element['normal'] as $attribute => $value){
                    if($value!=''){
                        echo $attribute.":".$value.";";
                    }
                }
                echo "}";
            }

            if(isset($element['hover']) && !empty($element['hover'])){
                echo "body ".$elem_id." .".$class.':hover{';
                foreach($element['hover'] as $attribute => $value){
                    if(!empty($value)){
                        echo $attribute.":".$value.";";
                    }
                }
                echo "}";
            }

        }
    /* Custom CSS from custom settings */
    if(isset($settings['_categdisp-custom-css']) && !empty($settings['_categdisp-custom-css'])){
        echo stripslashes($settings['_categdisp-custom-css']);
    }

           /* Media Query from custom settings */

    $breakpoints = array(
        'desktop' => '@media (min-width: 992px)',
        'tablet' => '@media (min-width: 768px) and (max-width: 991px)',
        'mobile' => '@media (max-width: 767px)',
    );
    if(isset($settings['media_query']) && !empty($settings['media_query'])){
        foreach($settings['media_query'] as $device => $media_query ){
            echo $breakpoints[$device];
            echo '{';
                foreach($media_query as $class => $props){
                    if(isset($props['normal']) && !empty($props['normal'])){
                        echo "body ".$elem_id." .".$class."{";
                            foreach($props['normal'] as $attribute => $value){
                                if($value!=''){
                                    echo $attribute.":".$value.";";
                                }
                            }
                        echo "}";
                    }
                    if(isset($props['hover']) && !empty($props['hover'])){
                        echo "body ".$elem_id." .".$class.":hover{";
                            foreach($props['hover'] as $attribute => $value){
                                if($value!=''){
                                    echo $attribute.":".$value.";";
                                }
                            }
                        echo "}";
                    }
                   

                }
            echo '}';

        }
    }
    ?>
</style>
